### ISSUE TITLE
Failure to generate __JsonHelper class for models in the unnamed/default package.

### ISSUE THREAD

**Issue by TommyVisic** [Instagram/ig-json-parser#10]
A model that's not in a named package causes an error during code generation. Not that we should be putting types there to begin with...

Error:(5, 8) error: Unable to write injector for type Item: Illegal name .tem__JsonHelper

![screen shot 2014-09-18 at 3 07 21 pm](https://cloud.githubusercontent.com/assets/3027722/4326459/86a6e544-3f6f-11e4-827a-09b058fe1bdb.png)

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by aimango** [comment]
I'm going to close this since it's standard practice to have your classes in packages
