### ISSUE TITLE
Object__JsonHelper is not recognized by the compiler but can be used

### ISSUE THREAD

**Issue by ignaciod** [Instagram/ig-json-parser#17]
Hi everyone, using Android Studio I managed to generate the gen-src folder, with the generated Object_JsonHelper. 
My project tree looks like this:

app
  ->gen-src
          ->main->java->com.mypackage
 ->src
          ->main->java->com.mypackage

The compiler show the Object_JsonHelper as an error but the fact is that when I press the play button the apk is deployed on the device/emulator. How can I get rid of the compiler error?

I'm very fond on implementing this solution.

Thanks

**Comment by ttung** [comment]
Before you build, the autogenerated source is not there, so it can't find it.  Once the compiler has been invoked, it should generate the source and find it in the future.

**Comment by ignaciod** [comment]
Hi ttung, but with the generated files the compiler can't resolve the the Object_JsonHelper. It would be nice if you don't close the issue before give me a hand? Thanks

![image](https://cloud.githubusercontent.com/assets/5910365/5634820/43e973d2-95ca-11e4-87da-c3f89d93219b.png)

**Comment by ttung** [comment]
It can't possibly run the app unless it can compile it.  If you can run the app, it means the compiler succeeded.  Android Studio may still be confused, but that's a different story.

Happy to help you debug this if you attach a sample project.

**Comment by ignaciod** [comment]
Ok I managed to make it work! Thanks.
