### ISSUE TITLE
Error while compile release apk with proguard

### ISSUE THREAD

**Issue by willyanto** [Instagram/ig-json-parser#18]
I got warning message when I build release apk for my app
"**Warning: com.instagram.common.json.annotation.processor.JsonAnnotationProcessor: can't find referenced field 'javax.annotation.processing.ProcessingEnvironment processingEnv' in program class com.instagram.common.json.annotation.processor.JsonAnnotationProcessor**"

But when I add **"-dontwarn com.instagram.common.json.annotation.processor.\*\*"**, it can be fixed.
Does not matter if I put   "-dontwarn com.instagram.common.json.annotation.processor.\*\*" in proguard file? Thanks

**Comment by ttung** [comment]
Yes, that warning is safe to ignore.

**Comment by ttung** [comment]
Did you try https://github.com/Instagram/ig-json-parser#proguard ?

**Comment by willyanto** [comment]
Yes, I already did using 
-dontwarn sun.misc.Unsafe
-dontwarn javax.annotation.**
-dontwarn com.instagram.common.json.annotation.processor.**

**Comment by ttung** [comment]
Ah okay.  The readme should probably be updated. :/

**Comment by willyanto** [comment]
Yes. And please give more example code. :) 
Like this problem #14 Consider support for serialization/deserialization of top level arrays
Thank you.

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
