### ISSUE TITLE
Jackson annotations?

### ISSUE THREAD

**Issue by eveliotc** [Instagram/ig-json-parser#21]
Hello,

Wondering why you decided to go with own annotations over say `JsonProperty` and friends from https://github.com/FasterXML/jackson-annotations

**Comment by ttung** [comment]
I needed additional parameters that JsonProperty does not convey.  I guess it's possible to lump them into a separate annotation, but it didn't really occur to me at the time.

If you feel strongly about it, happy to accept a PR.

**Comment by ttung** [comment]
I'm going to close this unless you have other questions.
