### ISSUE TITLE
Failing build

### ISSUE THREAD

**Issue by mfarid** [Instagram/ig-json-parser#34]
Hi 

I am trying to build the project but getting the below error:

1 warning
:util:processTestResources UP-TO-DATE
:util:testClasses
:util:test
:util:check
:util:build
:processorJar
:processorJavadoc
/home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/JsonFactoryHolder.java:5: error: package com.fasterxml.jackson.core does not exist
import com.fasterxml.jackson.core.JsonFactory;
                                 ^
/home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/JsonFactoryHolder.java:11: error: cannot find symbol
  public static final JsonFactory APP_FACTORY = new JsonFactory();
                      ^
  symbol:   class JsonFactory
  location: class JsonFactoryHolder
/home/ubuntu/projects/ig-json-parser/util/src/main/java/com/instagram/common/json/annotation/util/Console.java:5: error: package javax.annotation.concurrent does not exist
import javax.annotation.concurrent.GuardedBy;
                                  ^
/home/ubuntu/projects/ig-json-parser/processor/src/main/java/com/instagram/common/json/annotation/processor/JsonParserClassData.java:31: error: package com.fasterxml.jackson.core does not exist
import com.fasterxml.jackson.core.JsonGenerator;
                                 ^
/home/ubuntu/projects/ig-json-parser/processor/src/main/java/com/instagram/common/json/annotation/processor/JsonParserClassData.java:32: error: package com.fasterxml.jackson.core does not exist
import com.fasterxml.jackson.core.JsonParser;
                                 ^
/home/ubuntu/projects/ig-json-parser/processor/src/main/java/com/instagram/common/json/annotation/processor/JsonParserClassData.java:33: error: package com.fasterxml.jackson.core does not exist
import com.fasterxml.jackson.core.JsonToken;
                                 ^
/home/ubuntu/projects/ig-json-parser/processor/src/main/java/com/instagram/common/json/annotation/processor/StrFormat.java:8: error: package org.apache.commons.lang3.text does not exist
import org.apache.commons.lang3.text.StrSubstitutor;
                                    ^
/home/ubuntu/projects/ig-json-parser/util/src/main/java/com/instagram/common/json/annotation/util/Console.java:33: error: cannot find symbol
  @GuardedBy("Console.class")
   ^
  symbol:   class GuardedBy
  location: class Console
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:77: warning: no @param for packageName
  public JavaWriter emitPackage(String packageName) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:77: warning: no @return
  public JavaWriter emitPackage(String packageName) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:77: warning: no @throws for java.io.IOException
  public JavaWriter emitPackage(String packageName) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:96: warning: no @param for types
  public JavaWriter emitImports(String... types) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:96: warning: no @return
  public JavaWriter emitImports(String... types) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:96: warning: no @throws for java.io.IOException
  public JavaWriter emitImports(String... types) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:104: warning: no @param for types
  public JavaWriter emitImports(Class<?>... types) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:104: warning: no @return
  public JavaWriter emitImports(Class<?>... types) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:104: warning: no @throws for java.io.IOException
  public JavaWriter emitImports(Class<?>... types) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:116: warning: no @param for types
  public JavaWriter emitImports(Collection<String> types) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:116: warning: no @return
  public JavaWriter emitImports(Collection<String> types) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:116: warning: no @throws for java.io.IOException
  public JavaWriter emitImports(Collection<String> types) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:136: warning: no @param for types
  public JavaWriter emitStaticImports(String... types) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:136: warning: no @return
  public JavaWriter emitStaticImports(String... types) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:136: warning: no @throws for java.io.IOException
  public JavaWriter emitStaticImports(String... types) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:144: warning: no @param for types
  public JavaWriter emitStaticImports(Collection<String> types) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:144: warning: no @return
  public JavaWriter emitStaticImports(Collection<String> types) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:144: warning: no @throws for java.io.IOException
  public JavaWriter emitStaticImports(Collection<String> types) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:175: warning: no @param for type
  public String compressType(String type) {
                ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:175: warning: no @return
  public String compressType(String type) {
                ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:243: warning: no @return
  public JavaWriter beginInitializer(boolean isStatic) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:243: warning: no @throws for java.io.IOException
  public JavaWriter beginInitializer(boolean isStatic) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:256: warning: no @return
  public JavaWriter endInitializer() throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:256: warning: no @throws for java.io.IOException
  public JavaWriter endInitializer() throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:268: warning: no @param for type
  public JavaWriter beginType(String type, String kind) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:268: warning: no @return
  public JavaWriter beginType(String type, String kind) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:268: warning: no @throws for java.io.IOException
  public JavaWriter beginType(String type, String kind) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:277: warning: no @param for type
  public JavaWriter beginType(String type, String kind, Set<Modifier> modifiers)
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:277: warning: no @param for modifiers
  public JavaWriter beginType(String type, String kind, Set<Modifier> modifiers)
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:277: warning: no @return
  public JavaWriter beginType(String type, String kind, Set<Modifier> modifiers)
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:277: warning: no @throws for java.io.IOException
  public JavaWriter beginType(String type, String kind, Set<Modifier> modifiers)
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:288: warning: no @param for type
  public JavaWriter beginType(String type, String kind, Set<Modifier> modifiers, String extendsType,
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:288: warning: no @param for modifiers
  public JavaWriter beginType(String type, String kind, Set<Modifier> modifiers, String extendsType,
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:288: warning: no @param for implementsTypes
  public JavaWriter beginType(String type, String kind, Set<Modifier> modifiers, String extendsType,
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:288: warning: no @return
  public JavaWriter beginType(String type, String kind, Set<Modifier> modifiers, String extendsType,
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:288: warning: no @throws for java.io.IOException
  public JavaWriter beginType(String type, String kind, Set<Modifier> modifiers, String extendsType,
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:317: warning: no @return
  public JavaWriter endType() throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:317: warning: no @throws for java.io.IOException
  public JavaWriter endType() throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:326: warning: no @param for type
  public JavaWriter emitField(String type, String name) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:326: warning: no @param for name
  public JavaWriter emitField(String type, String name) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:326: warning: no @return
  public JavaWriter emitField(String type, String name) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:326: warning: no @throws for java.io.IOException
  public JavaWriter emitField(String type, String name) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:331: warning: no @param for type
  public JavaWriter emitField(String type, String name, Set<Modifier> modifiers)
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:331: warning: no @param for name
  public JavaWriter emitField(String type, String name, Set<Modifier> modifiers)
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:331: warning: no @param for modifiers
  public JavaWriter emitField(String type, String name, Set<Modifier> modifiers)
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:331: warning: no @return
  public JavaWriter emitField(String type, String name, Set<Modifier> modifiers)
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:331: warning: no @throws for java.io.IOException
  public JavaWriter emitField(String type, String name, Set<Modifier> modifiers)
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:337: warning: no @param for type
  public JavaWriter emitField(String type, String name, Set<Modifier> modifiers,
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:337: warning: no @param for name
  public JavaWriter emitField(String type, String name, Set<Modifier> modifiers,
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:337: warning: no @param for modifiers
  public JavaWriter emitField(String type, String name, Set<Modifier> modifiers,
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:337: warning: no @param for initialValue
  public JavaWriter emitField(String type, String name, Set<Modifier> modifiers,
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:337: warning: no @return
  public JavaWriter emitField(String type, String name, Set<Modifier> modifiers,
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:337: warning: no @throws for java.io.IOException
  public JavaWriter emitField(String type, String name, Set<Modifier> modifiers,
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:372: warning: no @return
  public JavaWriter beginMethod(String returnType, String name, Set<Modifier> modifiers,
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:372: warning: no @throws for java.io.IOException
  public JavaWriter beginMethod(String returnType, String name, Set<Modifier> modifiers,
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:390: warning: no @return
  public JavaWriter beginMethod(String returnType, String name, Set<Modifier> modifiers,
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:390: warning: no @throws for java.io.IOException
  public JavaWriter beginMethod(String returnType, String name, Set<Modifier> modifiers,
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:448: warning: no @param for javadoc
  public JavaWriter emitJavadoc(String javadoc, Object... params) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:448: warning: no @param for params
  public JavaWriter emitJavadoc(String javadoc, Object... params) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:448: warning: no @return
  public JavaWriter emitJavadoc(String javadoc, Object... params) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:448: warning: no @throws for java.io.IOException
  public JavaWriter emitJavadoc(String javadoc, Object... params) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:468: warning: no @param for comment
  public JavaWriter emitSingleLineComment(String comment, Object... args) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:468: warning: no @param for args
  public JavaWriter emitSingleLineComment(String comment, Object... args) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:468: warning: no @return
  public JavaWriter emitSingleLineComment(String comment, Object... args) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:468: warning: no @throws for java.io.IOException
  public JavaWriter emitSingleLineComment(String comment, Object... args) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:492: warning: no @param for name
  public JavaWriter emitEnumValue(String name, boolean isLast) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:492: warning: no @param for isLast
  public JavaWriter emitEnumValue(String name, boolean isLast) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:492: warning: no @return
  public JavaWriter emitEnumValue(String name, boolean isLast) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:492: warning: no @throws for java.io.IOException
  public JavaWriter emitEnumValue(String name, boolean isLast) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:504: warning: no @param for names
  public JavaWriter emitEnumValues(Iterable<String> names) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:504: warning: no @return
  public JavaWriter emitEnumValues(Iterable<String> names) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:504: warning: no @throws for java.io.IOException
  public JavaWriter emitEnumValues(Iterable<String> names) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:520: warning: no @param for annotation
  public JavaWriter emitAnnotation(String annotation) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:520: warning: no @return
  public JavaWriter emitAnnotation(String annotation) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:520: warning: no @throws for java.io.IOException
  public JavaWriter emitAnnotation(String annotation) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:525: warning: no @param for annotationType
  public JavaWriter emitAnnotation(Class<? extends Annotation> annotationType) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:525: warning: no @return
  public JavaWriter emitAnnotation(Class<? extends Annotation> annotationType) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:525: warning: no @throws for java.io.IOException
  public JavaWriter emitAnnotation(Class<? extends Annotation> annotationType) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:536: warning: no @param for annotationType
  public JavaWriter emitAnnotation(Class<? extends Annotation> annotationType, Object value)
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:536: warning: no @return
  public JavaWriter emitAnnotation(Class<? extends Annotation> annotationType, Object value)
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:536: warning: no @throws for java.io.IOException
  public JavaWriter emitAnnotation(Class<? extends Annotation> annotationType, Object value)
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:548: warning: no @param for annotation
  public JavaWriter emitAnnotation(String annotation, Object value) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:548: warning: no @return
  public JavaWriter emitAnnotation(String annotation, Object value) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:548: warning: no @throws for java.io.IOException
  public JavaWriter emitAnnotation(String annotation, Object value) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:560: warning: no @param for annotationType
  public JavaWriter emitAnnotation(Class<? extends Annotation> annotationType,
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:560: warning: no @param for attributes
  public JavaWriter emitAnnotation(Class<? extends Annotation> annotationType,
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:560: warning: no @return
  public JavaWriter emitAnnotation(Class<? extends Annotation> annotationType,
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:560: warning: no @throws for java.io.IOException
  public JavaWriter emitAnnotation(Class<? extends Annotation> annotationType,
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:572: warning: no @param for annotation
  public JavaWriter emitAnnotation(String annotation, Map<String, ?> attributes)
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:572: warning: no @return
  public JavaWriter emitAnnotation(String annotation, Map<String, ?> attributes)
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:572: warning: no @throws for java.io.IOException
  public JavaWriter emitAnnotation(String annotation, Map<String, ?> attributes)
                    ^
/home/ubuntu/projects/ig-json-parser/javawriter/src/main/java/com/instagram/javawriter/JavaWriter.java:661: warning: no @param for args
  public JavaWriter emitStatement(String pattern, Object... args) throws IOException {
                    ^
/home/ubuntu/projects/ig-json-parser/util/src/main/java/com/instagram/common/json/annotation/util/ProcessorClassData.java:44: error: reference not found
- {@link Class#getQualifiedName()}.
          ^
  /home/ubuntu/projects/ig-json-parser/util/src/main/java/com/instagram/common/json/annotation/util/TypeUtils.java:207: error: self-closing element not allowed
- <p/>
   ^
  /home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/annotation/JsonField.java:89: error: no summary or caption for table
- </table>
   ^
  /home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/annotation/JsonField.java:95: error: self-closing element not allowed
- <p/>
   ^
  /home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/annotation/JsonField.java:133: error: self-closing element not allowed
- <p/>
   ^
  /home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/annotation/JsonField.java:148: error: invalid entity &#x2714;
-     <td>&#x2714;</td>
           ^
  /home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/annotation/JsonField.java:149: error: invalid entity &#x2714;
-     <td>&#x2714;</td>
           ^
  /home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/annotation/JsonField.java:150: error: invalid entity &#x2714;
-     <td>&#x2714;</td>
           ^
  /home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/annotation/JsonField.java:151: error: invalid entity &#x2717;
-     <td>&#x2717;</td>
           ^
  /home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/annotation/JsonField.java:152: error: invalid entity &#x2714;
-     <td>&#x2714;</td>
           ^
  /home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/annotation/JsonField.java:153: error: invalid entity &#x2717;
-     <td>&#x2717;</td>
           ^
  /home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/annotation/JsonField.java:157: error: invalid entity &#x2714;
-     <td>&#x2714;</td>
           ^
  /home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/annotation/JsonField.java:158: error: invalid entity &#x2714;
-     <td>&#x2714;</td>
           ^
  /home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/annotation/JsonField.java:159: error: invalid entity &#x2714;
-     <td>&#x2714;</td>
           ^
  /home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/annotation/JsonField.java:160: error: invalid entity &#x2717;
-     <td>&#x2717;</td>
           ^
  /home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/annotation/JsonField.java:161: error: invalid entity &#x2717;
-     <td>&#x2717;</td>
           ^
  /home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/annotation/JsonField.java:162: error: invalid entity &#x2714;
-     <td>&#x2714;</td>
           ^
  /home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/annotation/JsonField.java:166: error: invalid entity &#x2714;
-     <td>&#x2714;</td>
           ^
  /home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/annotation/JsonField.java:167: error: invalid entity &#x2717;
-     <td>&#x2717;</td>
           ^
  /home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/annotation/JsonField.java:168: error: invalid entity &#x2717;
-     <td>&#x2717;</td>
           ^
  /home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/annotation/JsonField.java:169: error: invalid entity &#x2714;
-     <td>&#x2714;</td>
           ^
  /home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/annotation/JsonField.java:170: error: invalid entity &#x2717;
-     <td>&#x2717;</td>
           ^
  /home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/annotation/JsonField.java:171: error: invalid entity &#x2717;
-     <td>&#x2717;</td>
           ^
  /home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/annotation/JsonField.java:175: error: invalid entity &#x2714;
-     <td>&#x2714;</td>
           ^
  /home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/annotation/JsonField.java:176: error: invalid entity &#x2717;
-     <td>&#x2717;</td>
           ^
  /home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/annotation/JsonField.java:177: error: invalid entity &#x2717;
-     <td>&#x2717;</td>
           ^
  /home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/annotation/JsonField.java:178: error: invalid entity &#x2714;
-     <td>&#x2714;</td>
           ^
  /home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/annotation/JsonField.java:179: error: invalid entity &#x2717;
-     <td>&#x2717;</td>
           ^
  /home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/annotation/JsonField.java:180: error: invalid entity &#x2714;
-     <td>&#x2714;</td>
           ^
  /home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/annotation/JsonField.java:182: error: no summary or caption for table
- </table>
   ^
  /home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/annotation/JsonField.java:183: error: self-closing element not allowed
- <p/>
   ^
  /home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/annotation/JsonField.java:49: error: reference not found
- This string allows consumers to override how we extract the value from the {@link JsonParser}
                                                                                     ^
  /home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/annotation/JsonField.java:54: error: reference not found
-     <td>the instance of {@link JsonParser} being read from
                                  ^
  /home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/annotation/JsonField.java:67: error: no summary or caption for table
- </table>
   ^
  /home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/annotation/JsonField.java:22: error: reference not found
- occurred, so we are forced to throw a {@link JsonException}.
                                                ^
  /home/ubuntu/projects/ig-json-parser/common/src/main/java/com/instagram/common/json/JsonFactoryHolder.java:8: error: reference not found
  - Holds the {@link JsonFactory} singleton.
                  ^
    36 errors
    100 warnings
    :processorJavadoc FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':processorJavadoc'.
  
  > Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): '/home/ubuntu/projects/ig-json-parser/build/tmp/processorJavadoc/javadoc.options'
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Thank you
Farid

**Comment by tkieft** [comment]
Hi @mfarid - Are you using the provided gradle wrapper? It invokes gradle 2.2. The project builds fine for me (although there are some warnings) by running `./gradlew build`

If this does not work for you, can you try running with --stacktrace or --info or --debug to get more logging output? And/or pasting in the generated javadoc options file referenced at the bottom of the output?

**Comment by ttung** [comment]
Were you by any chance using jdk8?  The project doesn't play well with JDK8, but I'm fixing that in an upcoming patch.

**Comment by kangzhang** [comment]
doesn't seem we have a repro step, let's close this one?

**Comment by ttung** [comment]
I think it was fixed in https://github.com/Instagram/ig-json-parser/commit/88161d8fce27ac75af9672fd944c347574e65ee0
