### ISSUE TITLE
This library is not compatible JDK7 anymore

### ISSUE THREAD

**Issue by anthony-skr** [Instagram/ig-json-parser#38]
As per gradle dependencies versions :

```
|    +--- com.instagram:ig-json-parser-processor:0.0.6
|    |    +--- com.fasterxml.jackson.core:jackson-core:[2.2.3,) -> 2.9.0-SNAPSHOT
|    |    +--- com.google.guava:guava:[12.0.1,) -> 21.0-SNAPSHOT
|    |    \--- org.apache.commons:commons-lang3:[3.1,) -> 3.5
```

ig-json-parser now will get Guava 21 which is only JDK8 compatible :
_The coming release (21.0) will require JDK 1.8, but we will begin providing a backport soon thereafter._
(see https://github.com/google/guava).

It totally breaks apps running on JDK7.

**Comment by ttung** [comment]
Is this an issue?  The processor can run on JDK8+ but the runtime library doesn't depend on Guava.

**Comment by nacho007** [comment]
Please fix!!! This is no longer compatible with JDK7!!!

**Comment by ttung** [comment]
What errors are you seeing?

________________________________

**Comment by nacho007** [comment]
Cant use it. Says i need to support Java 1.7 but when I put the backward compatibility in gradle file nothing happens and doesnt compile. Try the JAR but with no luck!

**Comment by ttung** [comment]
What error messages do you see? Can you post an example project?

________________________________

**Comment by nacho007** [comment]
Just create an empty project, with the latest AS and target the latest SDK's , compile the igparser in the gradle file, and try to run the project.

**Comment by kangzhang** [comment]
we have updated the gradle configuration. closing, feel free to re-open if the error is still there.
