### ISSUE TITLE
JDK Compatibility Error

### ISSUE THREAD

**Issue by nacho007** [Instagram/ig-json-parser#41]
Hi there
I'm facing an error, maybe someone can help. 
To reproduce the error:
-Create a new project. 
-Add the dependency (`compile group: 'com.instagram', name: 'ig-json-parser-processor', version: '0.0.6+'`)
-Run the app.
My result: the gradle task ends with an error, aborting.

Here a screenshot:

![image](https://cloud.githubusercontent.com/assets/7153136/21374754/d939924e-c707-11e6-8809-0795a1638005.png)

I'm using Android Studio 2.2
- compileSdkVersion 25
- buildToolsVersion "25.0.1"
- Java 1.8

I tried the solution of the screenshot but no luck. 

Thanks in advice!

**Comment by ttung** [comment]
@kangzhang i think the maven artifacts need to be updated.

**Comment by rbranson** [comment]
@kangzhang update the damn artifacts Kang

**Comment by ttung** [comment]
@kangzhang KANG!!

**Comment by nacho007** [comment]
Of course I opted several months ago to change the library! Good luck and nice work
