### ISSUE TITLE
using with annotationProcessor from android studio 3.0

### ISSUE THREAD

**Issue by af-abe** [Instagram/ig-json-parser#47]
Hi,

In the new version of gradle, the 'android-apt'-pligin is no longer compatible.

now you have to user 'annotationProcessor' instatof 'apt'

so far so good. 

I do the folowing:

1) Remove the class path for the apt from the build.gradle (Project: MyApplication)
`classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'`

2) Remove the plug in from the build.gradle (Module: app)
`apply plugin: 'android-apt'`

3) Change the dependencies from apt to the new annotationProcessor
`annotationProcessor 'com.github.instagram.ig-json-parser:processor:master-SNAPSHOT'`

gradle sync workes so far but the *__JsonHelper are not beeing generadet anymore!

Help?

**Comment by kangzhang** [comment]
hey André, I just took a look of the issue and tried to reproduce it on my end. I did hit some dependency issues but after fixing that everything seems working fine.

I've committed fixes for the deps issue and included some instructions in the ReadMe file about Android Studio 3.0+ integrations. Could you give it a try and let me know if it works for you now?

**Comment by kangzhang** [comment]
P.S.

Make sure you use `--refresh-dependencies` when you rebuild the project, otherwise the cached artifacts from jitpack may confuse gradle.

**Comment by af-abe** [comment]
it workes
nice job

**Comment by kangzhang** [comment]
cool, closing!
