### ISSUE TITLE
A Crash While getting image from mobile to server while replyinh in personal DM.

### ISSUE THREAD

**Issue by surajsahani** [Instagram/ig-json-parser#63]
![Screenshot_2020-08-23-14-19-42-909_com miui bugreport](https://user-images.githubusercontent.com/22853459/91021141-f7d4b900-e610-11ea-9f0c-0dbf43b36d3b.jpg)

**Comment by aimango** [comment]
Can you paste the actual stack trace text?

**Comment by aimango** [comment]
Oh this is unrelated to the actually library, so I'm closing this out.
