### ISSUE TITLE
Unable to build project: Could not resolve com.github.instagram.ig-json-parser:processor:master-SNAPSHOT

### ISSUE THREAD

**Issue by sarp** [Instagram/ig-json-parser#64]
Not sure if it's a transient issue with jitpack but recently I've stopped being able to build a project that has ig-json-parser dependency:

      > Could not resolve com.github.instagram.ig-json-parser:processor:master-SNAPSHOT.
         > Unable to load Maven meta-data from https://jitpack.io/com/github/instagram/ig-json-parser/processor/master-SNAPSHOT/maven-metadata.xml.
            > Could not HEAD 'https://jitpack.io/com/github/instagram/ig-json-parser/processor/master-SNAPSHOT/maven-metadata.xml'.
               > Read timed out

The URL mentioned doesn't load on my computer. Could you confirm that README instructions still work?

**Comment by aimango** [comment]
@Sarp Can you try updating the dependencies based on this: https://jitpack.io/#Instagram/ig-json-parser/-SNAPSHOT
I can update the Readme after confirming it works for you

**Comment by sarp** [comment]
Thanks for looking into this. README instructions seem to be correct, I'm able to build again
I think it was a transient issue with jitpack.io timing out (confirmed by https://status.jitpack.io/)
